In [2]:
import numpy as np

In [2]:
print(np.__version__)

2.3.3


Creating Arrays

In [3]:
a = [1,2,3, 4,5]
print(type(a))

<class 'list'>


In [4]:
b = np.array(a)
print(b)
print(type(b))


[1 2 3 4 5]
<class 'numpy.ndarray'>


Using Arange
- limited to float and integers


In [5]:
arr = np.arange(4.5)
print(arr)
print(type(arr))

[0. 1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [6]:
more = np.arange(9)
print(more)

[0 1 2 3 4 5 6 7 8]


In [7]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [12]:
print(np.ones(4,dtype=int))

[1 1 1 1]


In [14]:
print(np.ones((4,5),dtype=int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [16]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Linspace

In [21]:
#an array of x elements between a,b
np.linspace(2,6,3)
np.linspace(start=0,stop=3,endpoint=False)

array([0.  , 0.06, 0.12, 0.18, 0.24, 0.3 , 0.36, 0.42, 0.48, 0.54, 0.6 ,
       0.66, 0.72, 0.78, 0.84, 0.9 , 0.96, 1.02, 1.08, 1.14, 1.2 , 1.26,
       1.32, 1.38, 1.44, 1.5 , 1.56, 1.62, 1.68, 1.74, 1.8 , 1.86, 1.92,
       1.98, 2.04, 2.1 , 2.16, 2.22, 2.28, 2.34, 2.4 , 2.46, 2.52, 2.58,
       2.64, 2.7 , 2.76, 2.82, 2.88, 2.94])

Full

In [3]:
np.full(shape=(2,2),fill_value=5.2,dtype=float)

array([[5.2, 5.2],
       [5.2, 5.2]])

Random

In [25]:
np.random.random(2)

array([0.21335063, 0.70281596])

In [30]:
np.random.randint(40,50,(3,2),dtype=int)

array([[44, 45],
       [41, 43],
       [48, 42]], dtype=int32)

In [31]:
np.random.normal(loc = 2, scale = 1.5, size =3)

array([ 3.65481473e+00,  3.77843965e+00, -3.53596898e-03])

In [33]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Custom Arrays

In [34]:
#2 dimensional array
c=np.array([[1,2,3,4],[5,6,7,8]])
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


In [37]:
#counting the number of dimensions
c.ndim

2

In [38]:
c.size

8

In [39]:
c.shape

(2, 4)