Learning Numpy and doing some exercises on it. 

In [2]:
import numpy as np

In [3]:
np.array([0,1,2,3,4,5,6,7])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
np.array([0,1.2,3.4,5.,6,7], dtype='float32')

array([0. , 1.2, 3.4, 5. , 6. , 7. ], dtype=float32)

In [6]:
np.array([range(i,i+3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
#a 10 length array filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
#A 3*5 floating point array filled with ones
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
#An 2*4 array full of 5.47
np.full((2,4),5.47)

array([[5.47, 5.47, 5.47, 5.47],
       [5.47, 5.47, 5.47, 5.47]])

In [ ]:
#An array starting from 0, ending at 36 and stepping by 3
np.arange(0,36,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [ ]:
#An array of 10 values evenly spaces between 0 and 99
np.linspace(0,99,10)

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [21]:
np.random.random((3,3))

array([[0.02036939, 0.02225701, 0.97717782],
       [0.95007946, 0.12202093, 0.01660882],
       [0.78578281, 0.17528426, 0.03368418]])

In [ ]:
#An array with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 1.1462567 , -1.32080933,  1.20349934],
       [ 0.11156414, -0.23693096, -0.55906211],
       [ 0.3230434 ,  1.28813416,  0.97692857]])

In [31]:
#An array of randon 3*3 matrix from 0 to 7
np.random.randint(0,7,(3,3))

array([[6, 6, 5],
       [6, 3, 6],
       [2, 2, 0]], dtype=int32)

In [35]:
#A 3*3 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.empty(2)

array([5.43230922e-312, 7.29112202e-304])

In [61]:
np.random.seed(0)
a1=np.random.randint(10,size=6)
a2=np.random.randint(10, size=(2,3))
a3=np.random.randint(10,size=(2,4,2))
print(a2)

[[3 5 2]
 [4 7 6]]


In [66]:
print("a2.ndim:", a2.ndim)
print("a2 shape:", a2.shape)
print("a2 size:", a2.size)
print("a2 dtype:", a2.dtype)
print("a2 item size:", a2.itemsize)
print("a2 nbytes:", a2.nbytes)

a2.ndim: 2
a2 shape: (2, 3)
a2 size: 6
a2 dtype: int32
a2 item size: 4
a2 nbytes: 24


Array Indexing

In [3]:
x1 = np.array([2,3,4,5,7,6,1,9])
print(x1[0])
print(x1[-1])
print(x1[-2])

2
9
1


In [12]:
#indexing in multidimesionsl arrays
np.random.seed(1)
x2 = np.random.randint(0,7,(2,3))
print(x2)
print(x2[0,0])
print(x2[1,0])
print(x2[1,-1])

[[5 3 4]
 [0 1 3]]
5
0
3


In [77]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x1[0] = 3.197
print(x1)

[3 0 3 3 7 9]


Array Slicing and accessing Subarrays

In [22]:
a1 = np.arange(10,20)
print(a1)

[10 11 12 13 14 15 16 17 18 19]


In [30]:
print(a1[:3]) #first 3 elements
print(a1[3:]) #elements after the third poition
print(a1[3:7]) #middle sub array
print(a1[::2]) #every other element
print(a1[::-1])#reverse oder of the elements
print(a1[1::2]) #every other element from the 1st index
print(a1[5::-1]) #reversed from index 3

[10 11 12]
[13 14 15 16 17 18 19]
[13 14 15 16]
[10 12 14 16 18]
[19 18 17 16 15 14 13 12 11 10]
[11 13 15 17 19]
[15 14 13 12 11 10]


In [34]:
np.random.seed(0)
a2 = np.random.randint(2,16,(3,4))
print(a2)

[[14  7  2  5]
 [13  5  9 11]
 [ 5  7  4  6]]


In [ ]:
print(a2[:2,:3]) #the first 2 rows and 3 columns
print(a2[:3,::2]) #all rows and every other column
print(a2[::-1,::-1]) #reverse order of both columns and rows

[[14  7  2]
 [13  5  9]]
[[14  2]
 [13  9]
 [ 5  4]]
[[ 6  4  7  5]
 [11  9  5 13]
 [ 5  2  7 14]]
