# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

2.3.3


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [12]:
a=np.array([0,33,4,5.7])
print(a.size)

4


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\awendi joy\onedrive\documents\py data\stone\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    con

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
x1 = np.zeros(10)
x1[4]=1
print(x1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
np.arange(10,49,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [4]:
a1 = np.arange(11,22)
print(a1[::-1])

[21 20 19 18 17 16 15 14 13 12 11]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
np.random.randint(0,8,(3,3))

array([[3, 0, 2],
       [6, 5, 0],
       [0, 6, 5]], dtype=int32)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
b1=np.array([1,2,0,0,4,0])
indices = np.nonzero(b1)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [10]:
np.random.randint(0,10,(3,3,3))

array([[[9, 1, 1],
        [5, 2, 8],
        [4, 9, 7]],

       [[9, 1, 2],
        [5, 1, 4],
        [7, 1, 2]],

       [[1, 1, 1],
        [0, 2, 8],
        [0, 1, 8]]], dtype=int32)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
np.random.seed(0)
a5 = np.random.randint(37,513, (10,10))
print(a5)
print(a5.min())
print(a5.max())

[[209  84 154 229 360 288 232 396  46 248]
 [314 279 329 124 107 509 125 433 351 230]
 [ 76 124 211 125 374 202  62 370 109 302]
 [441 152 501 280 234 372 468 485 375 136]
 [509 214 280 322 184 184 435 460 325 486]
 [302 222 164  69  68 239 281 188 200 496]
 [407 220  65 327 165 165 457  90 426  75]
 [281 310 372 425 142  79 479  68 413 294]
 [358 462  94 328 395 156 304 467 119 128]
 [421 435 136  90 433 158 463 121 240 361]]
46
509


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
a7 = np.random.randint(0,30,(1,30))
print(a7)

[[ 4 20  8 14 15 20  3 26 23 15 13 21 21 16 17  5  9  3  0  5  0 17 18  4
   2 16 29  3  2 10]]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)