# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [8]:
a1 = np.random.randint(1,10,(3,3))
print(a1)

a2 = np.pad(a1, pad_width=1, mode = 'constant', constant_values=0)
print(a2)

[[3 7 5]
 [5 3 1]
 [2 6 5]]
[[0 0 0 0 0]
 [0 3 7 5 0]
 [0 5 3 1 0]
 [0 2 6 5 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# anything multiplied by nan is stil nan
# nan is never equal to anything, even itself
# comparison with nan is always false
# nan minus nan is still undefined so it will be nan
# sets use hashing not equality. Since np.nan is hashed
# la

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [9]:
a1 = np.diag([1,2,3,4], k=1)
print(a1)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [10]:
b2 = np.zeros((8,8), int)
b2[1::2, 0::2] = 1
b2[0::2, 1::2] = 1
print(b2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
shape = (6,7,8)

index = 100

a3 = np.unravel_index(index, shape)

print(a3)

(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
a3 = np.array([0,1])
print(a3)

[0 1]


In [28]:
checker = np.tile(a3,(8,4))
print(checker)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [33]:
#random matrix
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [43]:
ran = np.random.randint(3,26,(5,5),dtype=int)
print(ran)

[[14 17  8 13 25]
 [10 10 21 22  7]
 [ 9  5 16  5 22]
 [24 19  7 21 12]
 [ 3  7 16 13  6]]


In [45]:
n1 =ran_norm = ran/ran.max()
print(n1)

[[0.56 0.68 0.32 0.52 1.  ]
 [0.4  0.4  0.84 0.88 0.28]
 [0.36 0.2  0.64 0.2  0.88]
 [0.96 0.76 0.28 0.84 0.48]
 [0.12 0.28 0.64 0.52 0.24]]


In [48]:
n2 = ran_norm = (ran - ran.mean() /ran.std()) #has mean of zero and standard deviation of 1
print(n2)

[[11.96918154 14.96918154  5.96918154 10.96918154 22.96918154]
 [ 7.96918154  7.96918154 18.96918154 19.96918154  4.96918154]
 [ 6.96918154  2.96918154 13.96918154  2.96918154 19.96918154]
 [21.96918154 16.96918154  4.96918154 18.96918154  9.96918154]
 [ 0.96918154  4.96918154 13.96918154 10.96918154  3.96918154]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [50]:
color_dtype = np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
    ('a', np.uint8),
])

In [53]:
colors = np.array([(1,2,34,65), (67,4,0,128), (255,0,0,255), (65,34,2,1)], dtype=color_dtype)

In [54]:
print(colors['r'])        # array([255,   0,   0], dtype=uint8)
print(colors[1]['a'])     # 128
print(colors[2]) 

[  1  67 255  65]
128
(255, 0, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [49]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)